<?xml version="1.0" ?>
<robot name="ur5_barrett" xmlns:xacro="http://ros.org/wiki/xacro">
	
  <!-- common stuff -->
  <xacro:include filename="$(find ur5_barrett_description)/urdf/ur5.gazebo.urdf.xacro" />

  <!-- ur5 -->
  <xacro:include filename="$(find ur5_barrett_description)/urdf/ur5.urdf.xacro" />
  <xacro:include filename="$(find ur5_barrett_description)/urdf/ur5.transmission.xacro" />
	

	<xacro:include filename="$(find ur5_barrett_description)/urdf/kinect.xacro"/>
	<xacro:include filename="$(find ur5_barrett_description)/urdf/kinect_properties.xacro"/>
	<xacro:include filename="$(find ur5_barrett_description)/urdf/kinect_gazebo.urdf.xacro"/>

	<xacro:include filename="$(find ur5_barrett_description)/urdf/bh282.urdf.xacro"/>
	<xacro:include filename="$(find ur5_barrett_description)/urdf/bh282.gazebo"/>
	

	<!-- property list -->
	
	<xacro:property name="robot_stand_height" value="0.75"/>
	<xacro:property name="kinect_stand_length" value="0.9"/>
	<xacro:property name="kinect_stand_distance" value="0.10"/>
	<xacro:ur5_robot prefix="" joint_limited="false"/>
	
	<!-- color macros -->
	
	
	<xacro:macro name="material_orange_transparent">
		<material name="orange_transparent">
			<color rgba="1 0.5 0 0.4"/>
		</material>
	</xacro:macro>
	<xacro:macro name="material_blue_transparent">
		<material name="blue_transparent">
			<color rgba="0 0.8 1 0.4"/>
		</material>
	</xacro:macro>
	
	<xacro:material_orange_transparent />
	
	<xacro:material_blue_transparent />
	<!-- end of color macros -->

	
	<link name="world"/>
	<link name="stand">
		<visual>
		<geometry>
		<cylinder radius="0.0735" length="${robot_stand_height}"/>
		</geometry>
		<material name="orange_transparent"/>
		</visual>
		<collision>
		<geometry>
		<cylinder radius="0.0735" length="${robot_stand_height}"/>
		</geometry>
		<material name="blue_transparent"/>
		</collision>
	</link>
	
	<link name="kinect_stand_dist">
		<visual>
		<geometry>
		<cylinder radius="0.03" length="${kinect_stand_distance}"/>
		</geometry>
		<material name="orange_transparent"/>
		</visual>
		<collision>
		<geometry>
		<cylinder radius="0.03" length="${kinect_stand_distance}"/>
		</geometry>
		<material name="blue_transparent"/>
		</collision>
	</link>
	<link name="kinect_stand">
		<visual>
		<geometry>
		<cylinder radius="0.03" length="${kinect_stand_length}"/>
		</geometry>
		<material name="orange_transparent"/>
		</visual>
		<collision>
		<geometry>
		<cylinder radius="0.03" length="${kinect_stand_length}"/>
		</geometry>
		<material name="blue_transparent"/>
		</collision>
	</link>

	

	<!-- instantiating sensor definitions -->

	
	<sensor_kinect  parent="kinect_stand"/>
	<!-- end of sensor definitions -->
	<!-- fixing barrett hand to the ur5 -->
	
	
	<xacro:bhand_macro parent="ee_link" name="bh">
  <origin xyz="0 0 0" rpy="1.57 0 1.57" />
  	</xacro:bhand_macro>
	<!-- Hand attached to the arm -->

	<joint name="world_to_stand" type="fixed">
		<parent link="world"/>
		<child link="stand"/>
		<origin xyz="0 0 0" rpy="0 0 0"/>
	</joint>
	<joint name="base_to_kinect_stand_dist" type="fixed">
		<parent link="stand"/>
		<child link="kinect_stand_dist"/>
		<origin xyz="0 ${-(kinect_stand_distance*0.5)-0.0735} 0" rpy="1.57 0 0"/>
	</joint>
	<joint name="kinect_stand1" type="fixed">
		<parent link="kinect_stand_dist"/>
		<child link="kinect_stand"/>
		<origin xyz="0 ${kinect_stand_length*0.5} ${(kinect_stand_distance*0.5)+0.015}" rpy="-1.57 0 0"/>
	</joint>

		
	<joint name="stand_to_base" type="fixed">
		<parent link="stand"/>
		<!--child link="${arm_prefix}base_link"/-->
		<child link="base_link"/>
		<origin xyz="0 0 ${robot_stand_height * 0.5}" rpy="0 0 1.57"/>
	</joint>
		
	
</robot>
